// When executing JavaScript code, errors will most definitely occur.


// The try statement lets you test a block of code to check for errors.
// The catch statement lets you handle the error if any are present.
// The throw statement lets you make your own errors.
// The finally statement lets you execute code after try and catch.  
// The finally block runs regardless of the result of the try-catch block.


setTimeout(()=>{
    console.log('Hacking WiFi......');
},1000)


setTimeout(()=>{
    console.log('Fetching username and password......');
    console.log(rahul);
},2000)


try{
    setTimeout(()=>{
        console.log(kopal);
    },100)
}
catch(error){
    console.log('error');
}

    


setTimeout(()=>{
    console.log("Hacking rahul's facebook id......");
},3000)


setTimeout(()=>{
    console.log('Username and password of Rahul(7894433434)......');
},4000)



